[package]
name = "hackers_os"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
spin = "0.10.0"
volatile = "0.6.1"
x86_64 = { version = "0.15.2", features = ["instructions"] }
bootloader = "0.11.10"
uart_16550 = "0.3.2"
pc-keyboard = "0.8.0"
pic8259 = "0.10.1"

lazy_static = { version = "1.4", default-features = false }

[build-dependencies]

[package.metadata.bootimage]
target = "x86_64-hackers_os.json"